import 'package:flutter/material.dart';

import 'app_language.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = <Locale>[
    Locale('tk'),
    Locale('ru'),
    Locale('en'),
  ];

  static const delegate = _AppLocalizationsDelegate();

  static AppLocalizations of(BuildContext context) {
    final localizations = Localizations.of<AppLocalizations>(
      context,
      AppLocalizations,
    );
    assert(localizations != null, 'AppLocalizations not found in context');
    return localizations!;
  }

  String t(String key) {
    final languageCode = AppLanguage.fromCode(locale.languageCode).code;
    return _localizedValues[languageCode]?[key] ??
        _localizedValues['tk']![key] ??
        key;
  }

  String format(String key, [Map<String, String> values = const {}]) {
    var text = t(key);
    values.forEach((placeholder, value) {
      text = text.replaceAll('{$placeholder}', value);
    });
    return text;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return AppLocalizations.supportedLocales.any(
      (supported) => supported.languageCode == locale.languageCode,
    );
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) {
    return false;
  }
}

extension AppLocalizationsBuildContextX on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
}

const Map<String, Map<String, String>> _localizedValues = {
  'tk': {
    'navHome': 'Esasy',
    'navFederations': 'Federasiyalar',
    'navProfile': 'Profil',
    'commonCancel': 'Ýatyr',
    'commonStart': 'Başlat',
    'commonStop': 'Duruz',
    'commonContinue': 'Dowam et',
    'commonLoading': 'Ýüklenýär...',
    'commonSave': 'Ýatda sakla',
    'commonLive': 'Live',
    'commonUser': 'Ulanyjy',
    'languageTitle': 'Interfeys dili',
    'languageSubtitle': 'Programmany görkezýän diliňiz',
    'onboardingTitle': 'Hoş geldiňiz',
    'onboardingSubtitle':
        'Live netijeler, iň soňky täzelikler\nwe ýaryşlar - hemmesi bir ýerde.',
    'loginTitle': 'Ulgama gir',
    'signupTitle': 'Hasap döret',
    'emailHint': 'Email',
    'passwordHint': 'Açar sözi',
    'passwordHintPlain': 'Acar sozi',
    'confirmPasswordHint': 'Açar sözi gaýtala',
    'confirmPasswordHintPlain': 'Acar sozi gaytala',
    'loginInvalidPassword': 'Nädogry açar sözi',
    'loginEnterPassword': 'Parol giriziň',
    'loginEnterEmail': 'Email giriziň.',
    'loginEnterValidEmail': 'Dogry email giriziň.',
    'loginPasswordMin': 'Parol azyndan 8 simwol bolmaly.',
    'loginFailed': 'Ulgama girip bolmady. Täzeden synanyşyň.',
    'forgotPassword': 'Paroly unutdym',
    'noAccount': 'Hasabyňyz ýokmy?',
    'signUp': 'Agza bol',
    'haveAccount': 'Hasabyňyz barmy?',
    'signIn': 'Ulgama gir',
    'signupEnterEmail': 'Email giriziň.',
    'signupEnterValidEmail': 'Dogry email giriziň.',
    'signupUsernameHint': 'Ulanyjy ady',
    'signupEnterUsername': 'Ulanyjy adyny giriziň.',
    'signupUsernameTooShort': 'Ulanyjy ady azyndan 3 simwol bolmaly.',
    'signupEnterPassword': 'Parol giriziň.',
    'signupPasswordMin': 'Parol azyndan 8 simwol bolmaly.',
    'signupEnterConfirmPassword': 'Paroly gaýtadan giriziň.',
    'signupPasswordsDontMatch': 'Parollar deň däl.',
    'signupFailed': 'Hasap döredip bolmady. Täzeden synanyşyň.',
    'passwordMinInline': 'Açar sözi azyndan 8 simwol bolmaly',
    'passwordsDontMatchInline': 'Açar sözler deň däl',
    'verificationTitle': 'Tassyklama koduny giriziň',
    'verificationSubtitle': '{email} adresine ugradylyan 6 belgili kody giriň',
    'verificationEmailMissing': 'Email tapylmady',
    'verificationInvalidCode': 'Tassyklama kody nädogry.',
    'verificationResent': 'Kod täzeden ugradyldy.',
    'verificationResendFailed': 'Kody täzeden ugratyp bolmady.',
    'verificationResend': 'Täzeden ugrat',
    'verificationResending': 'Ugradylyar...',
    'verificationVerify': 'Tassykla',
    'forgotPasswordTitle': 'Paroly unutdym',
    'forgotPasswordPromptEmail': 'Email salgyny giriziň.',
    'forgotPasswordPromptCode':
        '{email} adresine ugradylyan 6 belgili kody\ngiriň',
    'forgotPasswordValidEmail': 'Dogry email salgyny giriziň.',
    'forgotPasswordCodeSendFailed': 'Kod ugratyp bolmady.',
    'forgotPasswordEnterCode': '6 belgili kody giriziň.',
    'forgotPasswordValidInfo': 'Maglumatlary dogry giriziň.',
    'forgotPasswordResetFailed': 'Paroly täzeden düzüp bolmady.',
    'forgotPasswordSendCode': 'Kody ugrat',
    'forgotPasswordSendingCode': 'Kod ugradylyar...',
    'forgotPasswordCodeHint': '6 belgili kod',
    'forgotPasswordConfirming': 'Tassyklyanyar...',
    'forgotPasswordNewPasswordHint': 'Täze açar sözi',
    'forgotPasswordReset': 'Paroly üýtget',
    'homeSearchHint': 'Gözleg...',
    'homeNewsLoadFailed': 'Habarlar ýüklenmedi.',
    'homeNoNews': 'Habar entek ýok.',
    'homeShowAllNews': 'Hemme habarlary görkez',
    'homeLive': 'Live',
    'newsNotFound': 'Habar tapylmady.',
    'newsBack': 'Yza gaýt',
    'federationsTitle': 'Sport Federasiyalary',
    'federationsSearchHint': 'Gözleg...',
    'federationsLoadFailed': 'Federasiýalar ýüklenip bilinmedi.',
    'federationsEmpty': 'Federasiýa ýok.',
    'federationsNoResults': 'Netijeleri tapylmady.',
    'federationNotFound': 'Federasiýa tapylmady.',
    'federationPresident': 'Prezidenti:',
    'federationAddress': 'Salgysy:',
    'federationPhone': 'Telefon belgisi:',
    'federationEmail': 'Email adresi:',
    'federationPhoneCopied': 'Telefon belgisi göçürildi',
    'federationEmailCopied': 'Email göçürildi',
    'commonCopied': 'Göçürildi',
    'profileLogoutTitle': 'Çykmak?',
    'profileLogoutBody': 'Hasabyňyzdan çykmak isleýärsiňizmi?',
    'profileLogout': 'Çykmak',
    'profileInfo': 'Profil maglumatlary',
    'profileNotifications': 'Habarnamalar',
    'profileSettings': 'Sazlamalar',
    'profileLanguage': 'Interfeys dili',
    'profileHelp': 'Habarlaşmak',
    'profileLegal': 'Ulanyş düzgünleri',
    'profileAbout': 'Biz barada',
    'profileTitle': 'Profil',
    'profileAdmin': 'Admin',
    'profileEdit': 'Redaktirle',
    'settingsTitle': 'Sazlamalar',
    'settingsSubtitle': 'Hasap we görkeziş tertibi',
    'settingsNotificationsGroup': 'Habarnamalar',
    'settingsPushNotifications': 'Push habarnamalary',
    'settingsLiveAlerts': 'Göni efir habarnamalary',
    'settingsPlayerGroup': 'Pleýer we maglumat',
    'settingsDataSaver': 'Data tygşytlamak (HLS)',
    'settingsAutoplay': 'Awto-pleý',
    'settingsAccountGroup': 'Hasap',
    'settingsChangePassword': 'Paroly üýtget',
    'editProfileSaved': 'Profil täzelendi.',
    'editProfilePickCamera': 'Kameradan al',
    'editProfilePickGallery': 'Galereýadan saýla',
    'editProfileAvatarFailed': 'Surat ýüklemek başartmady.',
    'editProfileAvatarForbidden': 'Diňe administrator surat ýükläp biler.',
    'editProfileSubtitle': 'Şahsy maglumatlaryňyzy täzeläň',
    'editProfileFullName': 'Doly ady',
    'editProfilePhone': 'Telefon belgisi',
    'editProfileSave': 'Üýtgeşmeleri ýatda sakla',
    'notificationsSubtitle': 'Iň soňky täzelikler we ýaýlymlar',
    'notificationsMarkAllRead': 'Ählisini okalan belläň',
    'notificationsEmpty': 'Häzirçe habarnamalar ýok',
    'notificationsMarkedRead': 'Ähli habarnamalar okalan diýlip bellendi.',
    'notificationLiveStartedTitle': 'Täze ýaýlym başlandy',
    'notificationLiveStartedSubtitle': 'Futbol oýny göni efirde — derrew goş!',
    'notificationNewsPublishedTitle': 'Täze habar paýlaşyldy',
    'notificationNewsPublishedSubtitle':
        'Sport bölüminde iň soňky täzelik elýeterli.',
    'notificationFederationUpdatedTitle': 'Federasiýa täzelendi',
    'notificationFederationUpdatedSubtitle':
        'Sport federasiyalar barada täze maglumatlar.',
    'notificationWelcomeTitle': 'Hoş geldiňiz!',
    'notificationWelcomeSubtitle': 'Sportal hasabyňyz işjeňleşdirildi.',
    'timeNow': 'Häzir',
    'time15MinAgo': '15 minut öň',
    'time2HoursAgo': '2 sagat öň',
    'timeYesterday': 'Düýn',
    'changePasswordTitle': 'Paroly üýtgetmek',
    'changePasswordSubtitle': 'E-poçtaňyza iberilen kod arkaly',
    'changePasswordEmailMissing': 'Hasap email tapylmady.',
    'changePasswordCodeSent': '6-belgili kod {email} adresine iberildi.',
    'changePasswordSendFailed': 'Kod iberip bolmady: {error}',
    'changePasswordEmptyFields': 'Ähli meýdançalary dolduryň.',
    'changePasswordMismatch': 'Parollar gabat gelmeýär.',
    'changePasswordTooShort': 'Parol azyndan 8 simwol bolmaly.',
    'changePasswordSuccess': 'Parol üstünlikli üýtgedildi.',
    'changePasswordFailed': 'Üýtgedip bolmady: {error}',
    'changePasswordStepOneTitle': '1-nji ädim — kod alyň',
    'changePasswordStepOneBody':
        'E-poçtaňyza 6-belgili tassyklama kody ibereris.',
    'changePasswordSendCode': 'Kody iber',
    'changePasswordResendCode': 'Täzeden iber',
    'changePasswordSending': 'Iberilýär...',
    'changePasswordStepTwoTitle': '2-nji ädim — täze parol',
    'changePasswordCodeHint': '6-belgili kod',
    'changePasswordNewPassword': 'Täze parol',
    'changePasswordConfirmPassword': 'Paroly tassykla',
    'aboutTitle': 'Biz barada',
    'aboutVersion': 'Wersiya 1.0.0',
    'aboutDescription':
        'Sportal — sport janköýerleri üçin göni efirler, sport täzelikleri we federasiyalar barada giňişleýin maglumatlary bir programmada birleşdirýär.',
    'aboutBuild': 'Build',
    'aboutWebsite': 'Web sahypa',
    'aboutCopyright': 'Awtorlyk',
    'aboutPrivacy': 'Gizlinlik syýasaty',
    'aboutTerms': 'Ulanyş düzgünleri',
    'helpTitle': 'Habarlaşmak',
    'helpSubtitle': 'Soraglar we goldaw',
    'helpEmailSub': 'E-poçta arkaly hat ibermek',
    'helpPhoneSub': 'Goldaw gullugy',
    'helpTelegramSub': 'Telegram kanaly',
    'helpInstagramSub': 'Instagram sahypa',
    'helpFaqTitle': 'Köp soralýan soraglar',
    'faqJoinStreamQ': 'Ýaýlyma nädip goşulmaly?',
    'faqJoinStreamA':
        'Esasy ekrandan "Live streams" düwmesine basyň, soň göni efirdäki ýaýlymy saýlap tomaşa ediň.',
    'faqAdminStartQ': 'Admin ýaýlymy nireden başlap bilýär?',
    'faqAdminStartA':
        'Ýaýlymlar bölümindäki "Go live" düwmesi diňe admin hasaplary üçin görünýär. Göni ýaýlym telefondan başlanylýar.',
    'faqObsQ': 'OBS kanaly näme?',
    'faqObsA':
        'OBS kanaly bilen kompýuterde OBS Studio-dan RTMP arkaly ýaýlym iberilýär. Telefonda diňe tomaşa edip bolýar.',
    'faqForgotPasswordQ': 'Paroly ýatdan çykarsam näme etmeli?',
    'faqForgotPasswordA':
        'Login ekranyndaky paroly dikeltmek baglanyşygyna basyp, e-poçtaňyza iberilen 6-belgili kod arkaly täze parol goýup bilersiňiz.',
    'legalTitle': 'Ulanyş düzgünleri',
    'legalSubtitle': 'Sportal ulanyjy ylalaşygy',
    'legalSection1Title': '1. Hyzmat barada',
    'legalSection1Body':
        'Sportal Türkmenistanyň sport täzeliklerini, federasiyalary we göni efirleri tomaşa etmek üçin programmadyr. Hyzmaty ulanmak bilen siz aşakdaky düzgünleri kabul edýärsiňiz.',
    'legalSection2Title': '2. Hasap',
    'legalSection2Body':
        'Hasaby döretmek üçin hakyky e-poçta gerek. Parolyňyzyň goragyna özüňiz jogapkär. Hasap arkaly bolup geçen her hili hereketler üçin ulanyjy jogapkär.',
    'legalSection3Title': '3. Mazmun',
    'legalSection3Body':
        'Ýaýlymdaky we teswirlerdäki paýlaşan mazmunyňyz kanunlara we ahlak kadalaryna laýyk bolmaly. Düzgüni bozýan mazmun pozulyp, hasap çäklendirilip biliner.',
    'legalSection4Title': '4. Gizlinlik',
    'legalSection4Body':
        'Sportal şahsy maglumatlary diňe hyzmaty üpjün etmek üçin ulanýar. Üçünji taraplara satylmaýar we paýlaşylmaýar.',
    'legalSection5Title': '5. Üýtgeşmeler',
    'legalSection5Body':
        'Bu düzgünler wagtal-wagtal täzelenip biliner. Esasy üýtgeşmeler barada habarnamalar arkaly mälim ediler.',
    'streamsOnlyAdmin': 'Diňe admin göni ýaýlym başlap biler.',
    'streamsNewTitle': 'Täze ýaýlym',
    'streamsTitleHint': 'Ýaýlymyň ady',
    'streamsSoon': 'Basym',
    'streamsSupportedSportsHint':
        'API_ENDPOINTS.md boýunça häzir diňe futbol we woleýbol streamlerini döretmek goldanylýar.',
    'streamsEnterTitle': 'Stream adyny giriziň.',
    'streamsBackendSportsOnly':
        'Häzir backend diňe futbol we woleýbol streamlerini kabul edýär.',
    'streamsCreateFailed': 'Ýaýlymy döredip bolmady.',
    'streamsDeleteTitle': 'Ýaýlymy poz?',
    'streamsDeleteBody': '"{title}" sanawdan aýrylar.',
    'streamsDeleteCancel': 'Goý bolsun',
    'streamsDeleteConfirm': 'Poz',
    'streamsDeleted': 'Ýaýlym pozuldy.',
    'streamsDeleteFailed': 'Ýaýlymy pozup bolmady.',
    'streamsNotLive': 'Bu ýaýlym häzir göni däl.',
    'streamsGoLive': 'Göni efire çyk',
    'streamsLoadFailed': 'Ýaýlymlar ýüklenmedi.',
    'streamsEmpty': 'Häzir göni ýaýlym ýok.',
    'streamsTitle': 'Göni ýaýlymlar',
    'streamsSportalLive': 'Sportal göni',
    'streamsKanalLive': 'Kanal göni',
    'streamsDeleting': 'Pozulýar...',
    'sportAll': 'Hemmesi',
    'sportFootball': 'Futbol',
    'sportBasketball': 'Basketbol',
    'sportTennis': 'Tennis',
    'sportVolleyball': 'Woleýbol',
    'sportBoxing': 'Boks',
    'sportMma': 'MMA',
    'sportFormulaOne': 'Formula 1',
    'publishCameraInitFailed': 'Kamera işledilip bilinmedi.',
    'publishStartPermission':
        'Göni ýaýlym başlap bolmady. Kamera we mikrofon rugsatlaryny açyň.',
    'publishStartFailed': 'Göni ýaýlym başlap bolmady. {error}',
    'publishVideoHandshakeFailed': 'Wideo baglanyşygy şowsuz boldy ({code}).',
    'publishSwitchCameraFailed': 'Kamerany çalşyp bolmady.',
    'publishCommentFailed': 'Teswir iberilip bilinmedi.',
    'publishStopTitle': 'Ýaýlym dursunmy?',
    'publishStopBody': 'Bu göni ýaýlymy häzir tamamlamak isleýärsiňizmi?',
    'commentsHint': 'Teswir ýaz...',
    'commentsHide': 'Teswirleri gizle',
    'commentsShow': 'Teswirleri görkez',
    'fallbackUser': 'Ulanyjy',
    'statusStarting': 'STARTING',
    'watchPlayerInitFailed': 'Pleýer işledilip bilinmedi.',
    'watchFailed': 'Bu ýaýlyma tomaşa edip bolmady.',
    'watchCommentFailed': 'Teswir iberilip bilinmedi.',
  },
  'ru': {
    'navHome': 'Главная',
    'navFederations': 'Федерации',
    'navProfile': 'Профиль',
    'commonCancel': 'Отмена',
    'commonStart': 'Начать',
    'commonStop': 'Остановить',
    'commonContinue': 'Продолжить',
    'commonLoading': 'Загрузка...',
    'commonSave': 'Сохранить',
    'commonLive': 'Live',
    'commonUser': 'Пользователь',
    'languageTitle': 'Язык интерфейса',
    'languageSubtitle': 'Язык отображения приложения',
    'onboardingTitle': 'Добро пожаловать',
    'onboardingSubtitle':
        'Live-результаты, последние новости\nи соревнования — все в одном месте.',
    'loginTitle': 'Войти',
    'signupTitle': 'Создать аккаунт',
    'emailHint': 'Email',
    'passwordHint': 'Пароль',
    'passwordHintPlain': 'Пароль',
    'confirmPasswordHint': 'Повторите пароль',
    'confirmPasswordHintPlain': 'Повторите пароль',
    'loginInvalidPassword': 'Неверный пароль',
    'loginEnterPassword': 'Введите пароль.',
    'loginEnterEmail': 'Введите email.',
    'loginEnterValidEmail': 'Введите корректный email.',
    'loginPasswordMin': 'Пароль должен содержать минимум 8 символов.',
    'loginFailed': 'Не удалось войти. Попробуйте снова.',
    'forgotPassword': 'Забыли пароль',
    'noAccount': 'Нет аккаунта?',
    'signUp': 'Регистрация',
    'haveAccount': 'Уже есть аккаунт?',
    'signIn': 'Войти',
    'signupEnterEmail': 'Введите email.',
    'signupEnterValidEmail': 'Введите корректный email.',
    'signupUsernameHint': 'Имя пользователя',
    'signupEnterUsername': 'Введите имя пользователя.',
    'signupUsernameTooShort':
        'Имя пользователя должно содержать не менее 3 символов.',
    'signupEnterPassword': 'Введите пароль.',
    'signupPasswordMin': 'Пароль должен содержать минимум 8 символов.',
    'signupEnterConfirmPassword': 'Повторно введите пароль.',
    'signupPasswordsDontMatch': 'Пароли не совпадают.',
    'signupFailed': 'Не удалось создать аккаунт. Попробуйте снова.',
    'passwordMinInline': 'Пароль должен содержать минимум 8 символов',
    'passwordsDontMatchInline': 'Пароли не совпадают',
    'verificationTitle': 'Введите код подтверждения',
    'verificationSubtitle': 'Введите 6-значный код, отправленный на {email}',
    'verificationEmailMissing': 'Email не найден',
    'verificationInvalidCode': 'Неверный код подтверждения.',
    'verificationResent': 'Код отправлен повторно.',
    'verificationResendFailed': 'Не удалось отправить код повторно.',
    'verificationResend': 'Отправить снова',
    'verificationResending': 'Отправка...',
    'verificationVerify': 'Подтвердить',
    'forgotPasswordTitle': 'Забыли пароль',
    'forgotPasswordPromptEmail': 'Введите email.',
    'forgotPasswordPromptCode':
        'Введите 6-значный код, отправленный на\n{email}',
    'forgotPasswordValidEmail': 'Введите корректный email.',
    'forgotPasswordCodeSendFailed': 'Не удалось отправить код.',
    'forgotPasswordEnterCode': 'Введите 6-значный код.',
    'forgotPasswordValidInfo': 'Введите данные корректно.',
    'forgotPasswordResetFailed': 'Не удалось сбросить пароль.',
    'forgotPasswordSendCode': 'Отправить код',
    'forgotPasswordSendingCode': 'Отправка кода...',
    'forgotPasswordCodeHint': '6-значный код',
    'forgotPasswordConfirming': 'Подтверждение...',
    'forgotPasswordNewPasswordHint': 'Новый пароль',
    'forgotPasswordReset': 'Сменить пароль',
    'homeSearchHint': 'Поиск...',
    'homeNewsLoadFailed': 'Новости не загрузились.',
    'homeNoNews': 'Новостей пока нет.',
    'homeShowAllNews': 'Показать все новости',
    'homeLive': 'Live',
    'newsNotFound': 'Новость не найдена.',
    'newsBack': 'Назад',
    'federationsTitle': 'Спортивные федерации',
    'federationsSearchHint': 'Поиск...',
    'federationsLoadFailed': 'Не удалось загрузить федерации.',
    'federationsEmpty': 'Федераций нет.',
    'federationsNoResults': 'Ничего не найдено.',
    'federationNotFound': 'Федерация не найдена.',
    'federationPresident': 'Президент:',
    'federationAddress': 'Адрес:',
    'federationPhone': 'Телефон:',
    'federationEmail': 'Email:',
    'federationPhoneCopied': 'Номер телефона скопирован',
    'federationEmailCopied': 'Email скопирован',
    'commonCopied': 'Скопировано',
    'profileLogoutTitle': 'Выйти?',
    'profileLogoutBody': 'Вы действительно хотите выйти из аккаунта?',
    'profileLogout': 'Выйти',
    'profileInfo': 'Данные профиля',
    'profileNotifications': 'Уведомления',
    'profileSettings': 'Настройки',
    'profileLanguage': 'Язык интерфейса',
    'profileHelp': 'Связаться',
    'profileLegal': 'Правила использования',
    'profileAbout': 'О приложении',
    'profileTitle': 'Профиль',
    'profileAdmin': 'Админ',
    'profileEdit': 'Редактировать',
    'settingsTitle': 'Настройки',
    'settingsSubtitle': 'Аккаунт и отображение',
    'settingsNotificationsGroup': 'Уведомления',
    'settingsPushNotifications': 'Push-уведомления',
    'settingsLiveAlerts': 'Уведомления о прямых эфирах',
    'settingsPlayerGroup': 'Плеер и данные',
    'settingsDataSaver': 'Экономия трафика (HLS)',
    'settingsAutoplay': 'Автовоспроизведение',
    'settingsAccountGroup': 'Аккаунт',
    'settingsChangePassword': 'Сменить пароль',
    'editProfileSaved': 'Профиль обновлён.',
    'editProfilePickCamera': 'Сделать снимок',
    'editProfilePickGallery': 'Выбрать из галереи',
    'editProfileAvatarFailed': 'Не удалось загрузить изображение.',
    'editProfileAvatarForbidden':
        'Загружать аватар может только администратор.',
    'editProfileSubtitle': 'Обновите личные данные',
    'editProfileFullName': 'Полное имя',
    'editProfilePhone': 'Номер телефона',
    'editProfileSave': 'Сохранить изменения',
    'notificationsSubtitle': 'Последние новости и трансляции',
    'notificationsMarkAllRead': 'Отметить все как прочитанное',
    'notificationsEmpty': 'Уведомлений пока нет',
    'notificationsMarkedRead': 'Все уведомления отмечены как прочитанные.',
    'notificationLiveStartedTitle': 'Началась новая трансляция',
    'notificationLiveStartedSubtitle':
        'Футбольный матч уже в прямом эфире — присоединяйтесь!',
    'notificationNewsPublishedTitle': 'Опубликована новая новость',
    'notificationNewsPublishedSubtitle':
        'В спортивном разделе доступна свежая новость.',
    'notificationFederationUpdatedTitle': 'Федерация обновлена',
    'notificationFederationUpdatedSubtitle':
        'Появилась новая информация о спортивных федерациях.',
    'notificationWelcomeTitle': 'Добро пожаловать!',
    'notificationWelcomeSubtitle': 'Ваш аккаунт Sportal активирован.',
    'timeNow': 'Сейчас',
    'time15MinAgo': '15 минут назад',
    'time2HoursAgo': '2 часа назад',
    'timeYesterday': 'Вчера',
    'changePasswordTitle': 'Смена пароля',
    'changePasswordSubtitle': 'Через код, отправленный на email',
    'changePasswordEmailMissing': 'Email аккаунта не найден.',
    'changePasswordCodeSent': '6-значный код отправлен на {email}.',
    'changePasswordSendFailed': 'Не удалось отправить код: {error}',
    'changePasswordEmptyFields': 'Заполните все поля.',
    'changePasswordMismatch': 'Пароли не совпадают.',
    'changePasswordTooShort': 'Пароль должен содержать минимум 8 символов.',
    'changePasswordSuccess': 'Пароль успешно изменен.',
    'changePasswordFailed': 'Не удалось изменить: {error}',
    'changePasswordStepOneTitle': 'Шаг 1 — получите код',
    'changePasswordStepOneBody':
        'Мы отправим 6-значный код подтверждения на ваш email.',
    'changePasswordSendCode': 'Отправить код',
    'changePasswordResendCode': 'Отправить снова',
    'changePasswordSending': 'Отправка...',
    'changePasswordStepTwoTitle': 'Шаг 2 — новый пароль',
    'changePasswordCodeHint': '6-значный код',
    'changePasswordNewPassword': 'Новый пароль',
    'changePasswordConfirmPassword': 'Подтвердите пароль',
    'aboutTitle': 'О приложении',
    'aboutVersion': 'Версия 1.0.0',
    'aboutDescription':
        'Sportal объединяет прямые эфиры, спортивные новости и подробную информацию о федерациях в одном приложении для любителей спорта.',
    'aboutBuild': 'Сборка',
    'aboutWebsite': 'Веб-сайт',
    'aboutCopyright': 'Авторские права',
    'aboutPrivacy': 'Политика конфиденциальности',
    'aboutTerms': 'Правила использования',
    'helpTitle': 'Связаться',
    'helpSubtitle': 'Вопросы и поддержка',
    'helpEmailSub': 'Написать по электронной почте',
    'helpPhoneSub': 'Служба поддержки',
    'helpTelegramSub': 'Канал Telegram',
    'helpInstagramSub': 'Страница Instagram',
    'helpFaqTitle': 'Часто задаваемые вопросы',
    'faqJoinStreamQ': 'Как присоединиться к трансляции?',
    'faqJoinStreamA':
        'На главном экране нажмите кнопку "Live streams", затем выберите прямой эфир и начните просмотр.',
    'faqAdminStartQ': 'Где админ может начать трансляцию?',
    'faqAdminStartA':
        'Кнопка "Go live" в разделе трансляций видна только администраторам. Прямой эфир запускается с телефона.',
    'faqObsQ': 'Что такое OBS-канал?',
    'faqObsA':
        'OBS-канал позволяет отправлять трансляцию из OBS Studio на компьютере через RTMP. На телефоне доступен только просмотр.',
    'faqForgotPasswordQ': 'Что делать, если забыл пароль?',
    'faqForgotPasswordA':
        'Нажмите ссылку восстановления пароля на экране входа и задайте новый пароль через 6-значный код, отправленный на email.',
    'legalTitle': 'Правила использования',
    'legalSubtitle': 'Пользовательское соглашение Sportal',
    'legalSection1Title': '1. О сервисе',
    'legalSection1Body':
        'Sportal — приложение для просмотра спортивных новостей, федераций и прямых эфиров Туркменистана. Используя сервис, вы принимаете следующие правила.',
    'legalSection2Title': '2. Аккаунт',
    'legalSection2Body':
        'Для создания аккаунта нужен действующий email. Вы сами отвечаете за безопасность своего пароля. Пользователь несет ответственность за любые действия, совершенные через аккаунт.',
    'legalSection3Title': '3. Контент',
    'legalSection3Body':
        'Контент, который вы публикуете в трансляциях и комментариях, должен соответствовать законам и нормам поведения. Контент, нарушающий правила, может быть удален, а аккаунт ограничен.',
    'legalSection4Title': '4. Конфиденциальность',
    'legalSection4Body':
        'Sportal использует персональные данные только для предоставления сервиса. Они не продаются и не передаются третьим лицам.',
    'legalSection5Title': '5. Изменения',
    'legalSection5Body':
        'Эти правила могут время от времени обновляться. О важных изменениях будет сообщено через уведомления.',
    'streamsOnlyAdmin': 'Только администратор может начать прямой эфир.',
    'streamsNewTitle': 'Новая трансляция',
    'streamsTitleHint': 'Название трансляции',
    'streamsSoon': 'Скоро',
    'streamsSupportedSportsHint':
        'Сейчас создание трансляций поддерживается только для футбола и волейбола.',
    'streamsEnterTitle': 'Введите название трансляции.',
    'streamsBackendSportsOnly':
        'Сейчас backend принимает только футбольные и волейбольные трансляции.',
    'streamsCreateFailed': 'Не удалось создать трансляцию.',
    'streamsDeleteTitle': 'Удалить трансляцию?',
    'streamsDeleteBody': '"{title}" будет удалена из списка.',
    'streamsDeleteCancel': 'Отмена',
    'streamsDeleteConfirm': 'Удалить',
    'streamsDeleted': 'Трансляция удалена.',
    'streamsDeleteFailed': 'Не удалось удалить трансляцию.',
    'streamsNotLive': 'Эта трансляция сейчас не в эфире.',
    'streamsGoLive': 'Начать эфир',
    'streamsLoadFailed': 'Не удалось загрузить трансляции.',
    'streamsEmpty': 'Сейчас нет прямых эфиров.',
    'streamsTitle': 'Прямые эфиры',
    'streamsSportalLive': 'Sportal live',
    'streamsKanalLive': 'Kanal live',
    'streamsDeleting': 'Удаление...',
    'sportAll': 'Все',
    'sportFootball': 'Футбол',
    'sportBasketball': 'Баскетбол',
    'sportTennis': 'Теннис',
    'sportVolleyball': 'Волейбол',
    'sportBoxing': 'Бокс',
    'sportMma': 'MMA',
    'sportFormulaOne': 'Формула 1',
    'publishCameraInitFailed': 'Не удалось инициализировать камеру.',
    'publishStartPermission':
        'Не удалось начать трансляцию. Разрешите доступ к камере и микрофону.',
    'publishStartFailed': 'Не удалось начать трансляцию. {error}',
    'publishVideoHandshakeFailed':
        'Не удалось установить видеосоединение ({code}).',
    'publishSwitchCameraFailed': 'Не удалось переключить камеру.',
    'publishCommentFailed': 'Не удалось отправить комментарий.',
    'publishStopTitle': 'Остановить трансляцию?',
    'publishStopBody': 'Вы хотите завершить этот прямой эфир сейчас?',
    'commentsHint': 'Напишите комментарий...',
    'commentsHide': 'Скрыть комментарии',
    'commentsShow': 'Показать комментарии',
    'fallbackUser': 'Пользователь',
    'statusStarting': 'ЗАПУСК',
    'watchPlayerInitFailed': 'Не удалось инициализировать плеер.',
    'watchFailed': 'Не удалось посмотреть эту трансляцию.',
    'watchCommentFailed': 'Не удалось отправить комментарий.',
  },
  'en': {
    'navHome': 'Home',
    'navFederations': 'Federations',
    'navProfile': 'Profile',
    'commonCancel': 'Cancel',
    'commonStart': 'Start',
    'commonStop': 'Stop',
    'commonContinue': 'Continue',
    'commonLoading': 'Loading...',
    'commonSave': 'Save',
    'commonLive': 'Live',
    'commonUser': 'User',
    'languageTitle': 'Interface language',
    'languageSubtitle': 'The language used by the app',
    'onboardingTitle': 'Welcome',
    'onboardingSubtitle':
        'Live scores, latest news\nand competitions — all in one place.',
    'loginTitle': 'Sign in',
    'signupTitle': 'Create account',
    'emailHint': 'Email',
    'passwordHint': 'Password',
    'passwordHintPlain': 'Password',
    'confirmPasswordHint': 'Repeat password',
    'confirmPasswordHintPlain': 'Repeat password',
    'loginInvalidPassword': 'Invalid password',
    'loginEnterPassword': 'Enter password.',
    'loginEnterEmail': 'Enter email.',
    'loginEnterValidEmail': 'Enter a valid email.',
    'loginPasswordMin': 'Password must be at least 8 characters.',
    'loginFailed': 'Could not log in. Please try again.',
    'forgotPassword': 'Forgot password',
    'noAccount': 'Don\'t have an account?',
    'signUp': 'Sign up',
    'haveAccount': 'Already have an account?',
    'signIn': 'Sign in',
    'signupEnterEmail': 'Enter email.',
    'signupEnterValidEmail': 'Enter a valid email.',
    'signupUsernameHint': 'Username',
    'signupEnterUsername': 'Enter username.',
    'signupUsernameTooShort': 'Username must be at least 3 characters.',
    'signupEnterPassword': 'Enter password.',
    'signupPasswordMin': 'Password must be at least 8 characters.',
    'signupEnterConfirmPassword': 'Repeat the password.',
    'signupPasswordsDontMatch': 'Passwords do not match.',
    'signupFailed': 'Could not create account. Please try again.',
    'passwordMinInline': 'Password must be at least 8 characters',
    'passwordsDontMatchInline': 'Passwords do not match',
    'verificationTitle': 'Enter verification code',
    'verificationSubtitle': 'Enter the 6-digit code sent to {email}',
    'verificationEmailMissing': 'Email not found',
    'verificationInvalidCode': 'Invalid verification code.',
    'verificationResent': 'Code sent again.',
    'verificationResendFailed': 'Could not resend code.',
    'verificationResend': 'Resend',
    'verificationResending': 'Sending...',
    'verificationVerify': 'Verify',
    'forgotPasswordTitle': 'Forgot password',
    'forgotPasswordPromptEmail': 'Enter your email.',
    'forgotPasswordPromptCode': 'Enter the 6-digit code sent to\n{email}',
    'forgotPasswordValidEmail': 'Enter a valid email address.',
    'forgotPasswordCodeSendFailed': 'Could not send code.',
    'forgotPasswordEnterCode': 'Enter the 6-digit code.',
    'forgotPasswordValidInfo': 'Enter valid information.',
    'forgotPasswordResetFailed': 'Could not reset password.',
    'forgotPasswordSendCode': 'Send code',
    'forgotPasswordSendingCode': 'Sending code...',
    'forgotPasswordCodeHint': '6-digit code',
    'forgotPasswordConfirming': 'Verifying...',
    'forgotPasswordNewPasswordHint': 'New password',
    'forgotPasswordReset': 'Change password',
    'homeSearchHint': 'Search...',
    'homeNewsLoadFailed': 'News failed to load.',
    'homeNoNews': 'No news yet.',
    'homeShowAllNews': 'Show all news',
    'homeLive': 'Live',
    'newsNotFound': 'News item not found.',
    'newsBack': 'Go back',
    'federationsTitle': 'Sports Federations',
    'federationsSearchHint': 'Search...',
    'federationsLoadFailed': 'Could not load federations.',
    'federationsEmpty': 'No federations.',
    'federationsNoResults': 'No results found.',
    'federationNotFound': 'Federation not found.',
    'federationPresident': 'President:',
    'federationAddress': 'Address:',
    'federationPhone': 'Phone number:',
    'federationEmail': 'Email address:',
    'federationPhoneCopied': 'Phone number copied',
    'federationEmailCopied': 'Email copied',
    'commonCopied': 'Copied',
    'profileLogoutTitle': 'Log out?',
    'profileLogoutBody': 'Do you really want to log out of your account?',
    'profileLogout': 'Log out',
    'profileInfo': 'Profile details',
    'profileNotifications': 'Notifications',
    'profileSettings': 'Settings',
    'profileLanguage': 'Interface language',
    'profileHelp': 'Contact',
    'profileLegal': 'Terms of use',
    'profileAbout': 'About',
    'profileTitle': 'Profile',
    'profileAdmin': 'Admin',
    'profileEdit': 'Edit',
    'settingsTitle': 'Settings',
    'settingsSubtitle': 'Account and display preferences',
    'settingsNotificationsGroup': 'Notifications',
    'settingsPushNotifications': 'Push notifications',
    'settingsLiveAlerts': 'Live stream alerts',
    'settingsPlayerGroup': 'Player and data',
    'settingsDataSaver': 'Data saver (HLS)',
    'settingsAutoplay': 'Autoplay',
    'settingsAccountGroup': 'Account',
    'settingsChangePassword': 'Change password',
    'editProfileSaved': 'Profile updated.',
    'editProfilePickCamera': 'Take a photo',
    'editProfilePickGallery': 'Choose from gallery',
    'editProfileAvatarFailed': 'Failed to upload image.',
    'editProfileAvatarForbidden': 'Only admins can upload an avatar.',
    'editProfileSubtitle': 'Update your personal information',
    'editProfileFullName': 'Full name',
    'editProfilePhone': 'Phone number',
    'editProfileSave': 'Save changes',
    'notificationsSubtitle': 'Latest news and streams',
    'notificationsMarkAllRead': 'Mark all as read',
    'notificationsEmpty': 'No notifications yet',
    'notificationsMarkedRead': 'All notifications marked as read.',
    'notificationLiveStartedTitle': 'A new stream started',
    'notificationLiveStartedSubtitle':
        'The football match is live now — join in!',
    'notificationNewsPublishedTitle': 'New article published',
    'notificationNewsPublishedSubtitle':
        'A fresh update is available in the sports section.',
    'notificationFederationUpdatedTitle': 'Federation updated',
    'notificationFederationUpdatedSubtitle':
        'New information about sports federations is available.',
    'notificationWelcomeTitle': 'Welcome!',
    'notificationWelcomeSubtitle': 'Your Sportal account has been activated.',
    'timeNow': 'Now',
    'time15MinAgo': '15 minutes ago',
    'time2HoursAgo': '2 hours ago',
    'timeYesterday': 'Yesterday',
    'changePasswordTitle': 'Change password',
    'changePasswordSubtitle': 'Use the code sent to your email',
    'changePasswordEmailMissing': 'Account email was not found.',
    'changePasswordCodeSent': 'A 6-digit code was sent to {email}.',
    'changePasswordSendFailed': 'Could not send code: {error}',
    'changePasswordEmptyFields': 'Fill in all fields.',
    'changePasswordMismatch': 'Passwords do not match.',
    'changePasswordTooShort': 'Password must be at least 8 characters.',
    'changePasswordSuccess': 'Password changed successfully.',
    'changePasswordFailed': 'Could not change password: {error}',
    'changePasswordStepOneTitle': 'Step 1 — get the code',
    'changePasswordStepOneBody':
        'We will send a 6-digit confirmation code to your email.',
    'changePasswordSendCode': 'Send code',
    'changePasswordResendCode': 'Resend',
    'changePasswordSending': 'Sending...',
    'changePasswordStepTwoTitle': 'Step 2 — new password',
    'changePasswordCodeHint': '6-digit code',
    'changePasswordNewPassword': 'New password',
    'changePasswordConfirmPassword': 'Confirm password',
    'aboutTitle': 'About',
    'aboutVersion': 'Version 1.0.0',
    'aboutDescription':
        'Sportal brings together live streams, sports news, and detailed federation information in one app for sports fans.',
    'aboutBuild': 'Build',
    'aboutWebsite': 'Website',
    'aboutCopyright': 'Copyright',
    'aboutPrivacy': 'Privacy policy',
    'aboutTerms': 'Terms of use',
    'helpTitle': 'Contact',
    'helpSubtitle': 'Questions and support',
    'helpEmailSub': 'Send an email',
    'helpPhoneSub': 'Support service',
    'helpTelegramSub': 'Telegram channel',
    'helpInstagramSub': 'Instagram page',
    'helpFaqTitle': 'Frequently asked questions',
    'faqJoinStreamQ': 'How do I join a stream?',
    'faqJoinStreamA':
        'From the home screen, tap the "Live streams" button, then choose the live stream and start watching.',
    'faqAdminStartQ': 'Where can an admin start a stream?',
    'faqAdminStartA':
        'The "Go live" button in the streams section is visible only to admin accounts. Live streaming starts from the phone.',
    'faqObsQ': 'What is an OBS channel?',
    'faqObsA':
        'An OBS channel lets you send a stream from OBS Studio on a computer over RTMP. On the phone, it is watch-only.',
    'faqForgotPasswordQ': 'What should I do if I forgot my password?',
    'faqForgotPasswordA':
        'Use the password recovery link on the login screen and set a new password with the 6-digit code sent to your email.',
    'legalTitle': 'Terms of use',
    'legalSubtitle': 'Sportal user agreement',
    'legalSection1Title': '1. About the service',
    'legalSection1Body':
        'Sportal is an app for watching sports news, federations, and live streams from Turkmenistan. By using the service, you accept the following rules.',
    'legalSection2Title': '2. Account',
    'legalSection2Body':
        'A valid email is required to create an account. You are responsible for keeping your password secure. The user is responsible for any actions performed through the account.',
    'legalSection3Title': '3. Content',
    'legalSection3Body':
        'Content you post in streams and comments must comply with laws and community standards. Violating content may be removed and the account may be restricted.',
    'legalSection4Title': '4. Privacy',
    'legalSection4Body':
        'Sportal uses personal data only to provide the service. It is not sold or shared with third parties.',
    'legalSection5Title': '5. Changes',
    'legalSection5Body':
        'These terms may be updated from time to time. Major changes will be communicated through notifications.',
    'streamsOnlyAdmin': 'Only admin can start a live stream.',
    'streamsNewTitle': 'New stream',
    'streamsTitleHint': 'Stream title',
    'streamsSoon': 'Soon',
    'streamsSupportedSportsHint':
        'Only football and volleyball streams can currently be created.',
    'streamsEnterTitle': 'Please enter a stream title.',
    'streamsBackendSportsOnly':
        'The backend currently accepts only football and volleyball streams.',
    'streamsCreateFailed': 'Could not create stream.',
    'streamsDeleteTitle': 'Delete stream?',
    'streamsDeleteBody': '"{title}" will be removed from the list.',
    'streamsDeleteCancel': 'Keep it',
    'streamsDeleteConfirm': 'Delete',
    'streamsDeleted': 'Stream deleted.',
    'streamsDeleteFailed': 'Could not delete stream.',
    'streamsNotLive': 'This stream is not live right now.',
    'streamsGoLive': 'Go live',
    'streamsLoadFailed': 'Streams could not load.',
    'streamsEmpty': 'No live streams right now.',
    'streamsTitle': 'Live streams',
    'streamsSportalLive': 'Sportal live',
    'streamsKanalLive': 'Kanal live',
    'streamsDeleting': 'Deleting...',
    'sportAll': 'All',
    'sportFootball': 'Football',
    'sportBasketball': 'Basketball',
    'sportTennis': 'Tennis',
    'sportVolleyball': 'Volleyball',
    'sportBoxing': 'Boxing',
    'sportMma': 'MMA',
    'sportFormulaOne': 'Formula 1',
    'publishCameraInitFailed': 'Camera initialization failed.',
    'publishStartPermission':
        'Could not start stream. Allow camera and microphone permissions.',
    'publishStartFailed': 'Could not start stream. {error}',
    'publishVideoHandshakeFailed': 'Video handshake failed ({code}).',
    'publishSwitchCameraFailed': 'Could not switch camera.',
    'publishCommentFailed': 'Comment could not be sent.',
    'publishStopTitle': 'Stop stream?',
    'publishStopBody': 'Do you want to end this live stream now?',
    'commentsHint': 'Write a comment...',
    'commentsHide': 'Hide comments',
    'commentsShow': 'Show comments',
    'fallbackUser': 'User',
    'statusStarting': 'STARTING',
    'watchPlayerInitFailed': 'Player initialization failed.',
    'watchFailed': 'Could not watch this stream.',
    'watchCommentFailed': 'Comment could not be sent.',
  },
};
